name: Change status of linked issue to "In Review"
on:
  pull_request:
    types: [opened, reopened]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    name: Get id of a linked issue
    steps:
      - name: Get linked issues of a PR
        env:
          GH_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }} 
          ORGANIZATION: your-org
          PROJECT_NUMBER: 
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          linked_issue_id="$( gh api graphql -f query='
          query($pr:ID!) {
            node(id: $pr) {
              ... on PullRequest {
                closingIssuesReferences(first:1, userLinkedOnly:false) {
                  totalCount
                  nodes { 
                    id 
                    projectItems(first: 5) {
                      nodes {
                        id
                      }
                    }
                  }
                }
              }
            }
          }' -f pr=$PR_ID --jq '.data.node.closingIssuesReferences.nodes[0].projectItems.nodes[0].id')"
          echo "ISSUE ID:"
          echo "$linked_issue_id"
          echo "PR_ID:"
          echo "${{env.PR_ID}}"
          echo "LINKED_ISSUE_ID=$linked_issue_id" >> $GITHUB_ENV
      - name: Change status to "In Review"
        env:
          GH_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
          PROJECT_ID: something 
          ISSUE_ID: ${{ env.LINKED_ISSUE_ID }}
          STATUS_FIELD_ID:
          BEING_WORKED_ON_OPTION_ID:
        run: |
          updatedAt="$( gh api graphql -f query='
          mutation($issueId:ID!, $projectId:ID!) {
            updateProjectV2ItemFieldValue(input: {projectId: $projectId, fieldId: "${{env.STATUS_FIELD_ID}}", itemId: $issueId, value: {singleSelectOptionId: "${{env.BEING_WORKED_ON_OPTION_ID}}"}}) {
              projectV2Item {
                type
                updatedAt
              }
            }
          }' -f issueId=$ISSUE_ID -f projectId=$PROJECT_ID  --jq '.data.updateProjectV2ItemFieldValue.projectV2Item.updatedAt')"
          